config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'users#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Post
    can :read, Comment
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_comments_counter
  after_destroy :decrement_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.last(5)
  end

  after_create :update_post_counter
  after_destroy :decrement_post_counter

  private

  def update_post_counter
    author.increment!(:post_counter)
  end

  def decrement_post_counter
    author.decrement!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_three_post
    posts.includes(:comments, :likes).last(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_authorization_check only: [:create]

  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments

    render json: @comments
  end

  def create
    post = Post.find(params[:post_id])
    author = User.find(comment_params[:author_id])
    @comment = post.comments.new(text: comment_params[:text], author:)
    respond_to do |format|
      if @comment.save
        format.json { render json: @comment, location: user_post_url(post.author, post) }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :author_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author, :comments).where(author_id: params[:user_id])

    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments

    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.new(author: current_user, **comment_params)
    respond_to do |_format|
      if @comment.save
        flash[:notice] = 'Comment created successfully!'
      else
        flash[:alert] = 'Comment was not created!'
      end
      redirect_to user_post_path(post.author, post)
    end
  end

  def destroy
    @comment.destroy

    flash[:notice] = 'Comment deleted successfully!'
    redirect_to user_post_path(current_user), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @like = post.likes.new(author: current_user)
    if @like.save
      flash[:notice] = 'Likes added succesfully!'
      redirect_to user_post_path(post.author, post)
    else
      flash[:alert] = 'Likes not added!'
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author, :comments).where(author_id: params[:user_id])

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes(:author, :comments, :likes).find_by(author_id: @user.id, id: params[:id])

    if @post
      @comment = Comment.new
      @like = Like.new
    else
      flash[:alert] = 'Post not found!'
      redirect_to user_post_path(@user, params[:id])
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params.merge(comments_counter: 0, likes_counter: 0))
    respond_to do |format|
      format.html do
        if @post.save
          flash[:notice] = 'Post created successfully!'
          redirect_to user_post_path(current_user, @post)
        else
          flash[:alert] = 'Post not created!'
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post deleted succesfully!'
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def admin?
    admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_comments_form.html.erb
<%= form_with model: [current_user, post, comment] do |form| %>
  <div class="mb-3">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control" %>
  </div>
  <div>
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/forms/_form.html.erb
<%= form_with model: [current_user, @post] do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control mb-3" %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control mb-3" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container my-3 py-3">
      </br>
      <%= render 'partials/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/partials/_comments.html.erb
<li class="border border-1 p-1 rounded mb-1 d-flex justify-content-between">
  <div>
    <span><%= comment.author.name %></span>:
    <span><%= comment.text %></span>
  </div>
  <div>
    <% if can? :destroy, comment %>
      <%= link_to 'delete', polymorphic_url([comment.post.author, comment.post, comment]), data: {
        turbo_method: :delete,
        turbo_confirm: 'Are you sure!'
        }, class: 'btn btn-danger btn-sm' 
      %>
    <% end %>
  </div>
</li>

app/views/partials/_posts.html.erb
<li class="card p-1">
  <span>
    <%= link_to post.title, user_post_path(@user, post), class: 'text-decoration-none' %>
  </span>
  <span><%= post.text %></span>
  <span class="text-end">
    <span>Comments: <%= post.comments_counter %></span>,
    <span>Likes: <%= post.likes_counter %></span>
  </span>
  <% if can? :destroy, post %>
    <%= link_to 'delete',polymorphic_url([post.author, post]), data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure'
    }, class: 'btn btn-outline-danger btn-sm align-self-start' %>
  <% end %>
</li>

app/views/partials/_users.html.erb
<div class="d-flex align-items-center gap-3">
  <div style="width: 70px">
    <% if user.photo.present? %>
      <%= image_tag user.photo, alt: user.name, class: "border border-2 rounded p-2 img-fluid" %>
    <% else %>
      <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Windows_10_Default_Profile_Picture.svg/2048px-Windows_10_Default_Profile_Picture.svg.png", alt: user.name, class: "border border-2 rounded rounded-circle p-2 img-fluid" %>
    <% end %>
  </div>
  <div class="card flex-fill p-1">
    <span class="d-block">
      <%= link_to user.name, user, class: 'nav-link fw-bold fs-5', 'data-user-id': 'users' %>
    </span>
    <span class="text-end fs-6">
      Number of posts: <%= user.post_counter %>
    </span>
  </div>
</div>

app/views/posts/index.html.erb
<section>
  <div class="mb-3">
    <%= render 'partials/users', user: @user %>
  </div>
  <div>
    <ul class="list-unstyled">
      <% @posts.each do |post| %>
        <li class="mb-3">
          <%= link_to user_post_path(@user, post), class: "nav-link" do %>
            <%= render 'partials/posts', post: post %>
          <% end %>
          <ul class="list-unstyled">
            <% post.recent_five_comments.each do |comment| %>
              <%= render 'partials/comments', comment: comment %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
  <button type="button" class="btn btn-outline-dark">Pagination</button>
</section>

app/views/posts/new.html.erb
<div>
<h2>Add new post</h2>
<%= render 'forms/form'%>
</div>

app/views/posts/show.html.erb
<% if @post %>
  <div class="card p-1 mb-1">
    <p class="mb-0"><%= @post.title %> by <%= @post.author.name %></p>
    <p class="text-end">
      <span>Comments: <%= @post.comments_counter %></span>,
      <span>Likes: <%= @post.likes_counter %></span>
    </p>
    <p><%= @post.text %></p>
    <div class="align-self-end">
      <%= form_with url: user_post_likes_path(current_user, @post), method: :post do |f| %>
        <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
        <%= f.submit "Like", class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= flash[:alert] %>
<% end %>
<ul class="list-unstyled">
  <% @post.comments.each do |comment| %>
    <%= render 'partials/comments', comment: comment %>
  <% end %>
</ul>
<%= render 'forms/comments_form', post: @post, comment: @comment%>

app/views/users/index.html.erb
<div class="mb-3 d-flex align-items-center justify-content-between">
  <h2>Welcome <%= current_user.name %>!</h2>
  <% if user_signed_in? %>
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger btn-sm' %>
  <% end %>
</div>
<div class="mb-3">
  <%= link_to 'New post', new_user_post_path(user_id: current_user.id), class: "btn btn-outline-secondary" %>
</div>
<ul class="list-unstyled">
  <% @users.each do |user| %>
    <li class="mb-3">
      <%= render 'partials/users', user: user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="mb-3">
  <div class="mb-3">
    <%= render 'partials/users', user: @user %>
  </div>
  <p class="card pb-3 ps-1">
    <span class="mb-3">Bio</span>
    <%= @user.bio %>
  </p>
</div>

<ul class="list-unstyled">
  <% @user.recent_three_post.each do |post| %>
    <div class="mb-3">
      <%= render 'partials/posts', post: post %>
    </div>
  <% end %>
</ul>

<%= link_to 'See all posts', user_posts_path(@user), class: "btn btn-outline-dark" %>